name: CodeCov
on: [push, pull_request]
jobs:
  run:
    name: test ${{ matrix.os }} / ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.11","3.12"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
    steps:
    - uses: actions/checkout@master
    - uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python }}
    - name: install deps
      run: |
        pdm use -f $PYTHON
        pdm install -d
    # https://github.com/actions/virtual-environments/issues/1187
    - name: tune linux network
      run: sudo ethtool -K eth0 tx off rx off

    - name: Cache Description documents
      id: cache-www-data
      uses: actions/cache@v3
      env:
        cache-name: cache-www-data
      with:
        path: ~/www-data/
        key: ${{ env.cache-name }}-20240527

    - if: ${{ steps.cache-www-data.outputs.cache-hit != 'true' }}
      name: Get description documents
      run: |
        mkdir ~/www-data
        wget --directory-prefix=~/www-data https://www.dmtf.org/sites/default/files/standards/documents/DSP2043_2024.1.zip
        wget --directory-prefix=~/www-data https://www.dmtf.org/sites/default/files/standards/documents/DSP8010_2024.1.zip
        wget --directory-prefix=~/www-data https://www.snia.org/sites/default/files/technical-work/swordfish/release/v1.2.6/zip/Swordfish_v1.2.6.zip
        unzip ~/www-data/Swordfish_v1.2.6.zip '*_Schema.zip' -d ~/www-data/
    - name: Setup description documents
      run: |
        mkdir -p src/aiopenapi3_redfish/description_documents/DSP8010/2024.1/
        unzip -j ~/www-data/DSP8010_2024.1.zip 'openapi/*.yaml' -d src/aiopenapi3_redfish/description_documents/DSP8010/2024.1/
        mkdir -p src/aiopenapi3_redfish/description_documents/Swordfish/v1.2.6/
        unzip -j ~/www-data/Swordfish_v1.2.6_Schema.zip  'yaml/*.yaml' -d src/aiopenapi3_redfish/description_documents/Swordfish/v1.2.6/
        pdm run pytest --cov=tests/test_description_documents --cov-report=xml:./coverage/reports/coverage-description_documents-tests.xml tests/description_documents_test.py
    - name: Generate coverage report (DSP 2043)
      run: |
        pdm run pytest --cov=src/aiopenapi3_redfish/ --cov-report=xml:./coverage/reports/coverage-dsp2043.xml       tests/dsp2043_test.py::test_dsp2043_file
        pdm run pytest --cov=tests/test_dsp2043.py   --cov-report=xml:./coverage/reports/coverage-dsp2043-tests.xml tests/dsp2043_test.py::test_dsp2043_file
    - name: Upload coverage to Codecov (core)
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        files: coverage-dsp2043.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: false
        flags: core
        name: codecov-aiopenapi3_redfish
        verbose: true
    - name: Upload coverage to Codecov (tests)
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        files: coverage-description_documents-tests.xml,coverage-dsp2043-tests.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: false
        flags: tests
        name: codecov-aiopenapi3_redfish-tests
        verbose: true
