name: CodeCov
on: [push, pull_request]
jobs:
  run:
    name: test ${{ matrix.os }} / ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.11","3.12"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
    steps:
    - uses: actions/checkout@master
    - uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python }}
    - name: install deps
      run: |
        pdm use -f $PYTHON
        pdm install -d
    - name: Setup description documents
      run: |
        pdm run pytest --cov=tests/test_description_documents --cov-report=xml:./coverage/reports/coverage-description_documents-tests.xml tests/description_documents_test.py
    - name: Generate coverage report (DSP 2043)
      run: |
        pdm run pytest --cov=src/aiopenapi3_redfish/ --cov-report=xml:./coverage/reports/coverage-dsp2043.xml       tests/dsp2043_test.py::test_dsp2043_file
        pdm run pytest --cov=tests/test_dsp2043.py   --cov-report=xml:./coverage/reports/coverage-dsp2043-tests.xml tests/dsp2043_test.py::test_dsp2043_file
    - name: Upload coverage to Codecov (core)
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        files: coverage-dsp2043.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: false
        flags: core
        name: codecov-aiopenapi3_redfish
        verbose: true
    - name: Upload coverage to Codecov (tests)
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        files: coverage-description_documents-tests.xml,coverage-dsp2043-tests.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: false
        flags: tests
        name: codecov-aiopenapi3_redfish-tests
        verbose: true
