from ..oem import Lookup
from .actions import Actions, Oem

from .service import (
    AsyncAccountService,
    AsyncCertificateService,
    AsyncChassis,
    AsyncEventService,
    AsyncFabric,
    AsyncJobService,
    AsyncLicenseService,
    AsyncSessionService,
    AsyncSystem,
    AsyncTaskService,
    AsyncTelemetryService,
    AsyncUpdateService,
)

from .collections import (
    ChassisCollection,
    ConnectionCollection,
    DriveCollection,
    EndpointCollection,
    EndpointGroupCollection,
    EthernetInterfaceCollection,
    FabricCollection,
    JobCollection,
    LogEntryCollection,
    LogServiceCollection,
    ManagerAccountCollection,
    ManagerCollection,
    NetworkAdapterCollection,
    NetworkDeviceFunctionCollection,
    NetworkPortCollection,
    PortCollection,
    SessionsCollection,
    StorageCollection,
    StorageControllerCollection,
    SwitchCollection,
    SystemsCollection,
    TaskCollection,
    VolumeCollection,
    ZoneCollection,
)

from .settings import AsyncBios


class Defaults(Lookup):
    detour = [
        Actions,
        Oem,
        AsyncAccountService,
        AsyncCertificateService,
        AsyncChassis,
        AsyncEventService,
        AsyncFabric,
        AsyncJobService,
        AsyncLicenseService,
        AsyncSessionService,
        AsyncSystem,
        AsyncTaskService,
        AsyncTelemetryService,
        AsyncUpdateService,
        ChassisCollection,
        ConnectionCollection,
        #        DriveCollection,
        EndpointCollection,
        EndpointGroupCollection,
        EthernetInterfaceCollection,
        FabricCollection,
        JobCollection,
        LogEntryCollection,
        LogServiceCollection,
        ManagerAccountCollection,
        ManagerCollection,
        NetworkAdapterCollection,
        NetworkDeviceFunctionCollection,
        NetworkPortCollection,
        PortCollection,
        SessionsCollection,
        StorageCollection,
        StorageControllerCollection,
        SwitchCollection,
        SystemsCollection,
        TaskCollection,
        VolumeCollection,
        ZoneCollection,
        AsyncBios,
    ]
